resources:
  - backend-deployment.yml
  - backend-service.yml
  - frontend-deployment.yml
  - frontend-service.yml
  - postgres-deployment.yml
  - postgres-service.yml
  - postgres-pvc.yml
  - ingress.yml
