apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  template:
    spec:
      containers:
      - name: frontend
        env:
        - name: REACT_APP_BACKEND_API_BASE_URL
          value: "http://myapp.local/api"
